const VOCAB_TOPICS = [
  {
    topic: 'Environment',
    words: [
      { term: 'biodiversity', pos: 'n.', def: 'the variety of plant and animal life in a habitat', ex: 'Protected areas help preserve biodiversity threatened by urban expansion.', col: 'loss of biodiversity' },
      { term: 'carbon footprint', pos: 'n.', def: 'the total greenhouse gases produced by an activity or person', ex: 'Many consumers now track their carbon footprint before choosing transport.', col: 'reduce one\'s carbon footprint' },
      { term: 'deforestation', pos: 'n.', def: 'the large-scale clearing of forests', ex: 'Deforestation in tropical regions accelerates both erosion and species loss.', col: 'rampant deforestation' },
      { term: 'ecosystem', pos: 'n.', def: 'a community of organisms interacting with their physical environment', ex: 'Wetland ecosystems naturally filter pollutants from agricultural runoff.', col: 'fragile ecosystem' },
      { term: 'emission', pos: 'n.', def: 'a substance released into the atmosphere, especially gases', ex: 'Tighter emission standards have improved air quality in several capitals.', col: 'carbon emission' },
      { term: 'conservation', pos: 'n.', def: 'the protection and careful management of natural resources', ex: 'Wildlife conservation depends on sustained funding and effective enforcement.', col: 'nature conservation' },
      { term: 'sustainable', pos: 'adj.', def: 'able to continue without depleting resources or harming the environment', ex: 'Cities require sustainable transport networks to ease congestion and pollution.', col: 'sustainable development' },
      { term: 'renewable', pos: 'adj.', def: 'replenished naturally and not permanently depleted', ex: 'Investment in renewable energy has risen sharply over the past decade.', col: 'renewable resources' },
      { term: 'mitigation', pos: 'n.', def: 'action to reduce the severity of an environmental problem', ex: 'Climate mitigation policies now target households as well as heavy industry.', col: 'climate change mitigation' },
      { term: 'pollution', pos: 'n.', def: 'the introduction of harmful substances into the environment', ex: 'Industrial pollution disproportionately affects low-income urban districts.', col: 'air pollution' },
      { term: 'habitat', pos: 'n.', def: 'the natural environment where a species lives', ex: 'Fragmented habitat increases extinction risk for large mammals.', col: 'natural habitat' },
      { term: 'desertification', pos: 'n.', def: 'the process by which fertile land becomes desert', ex: 'Overgrazing and poor irrigation contribute to desertification in arid zones.', col: 'combat desertification' },
      { term: 'contamination', pos: 'n.', def: 'the presence of a harmful substance in soil, water, or air', ex: 'Groundwater contamination poses serious long-term public health risks.', col: 'soil contamination' },
      { term: 'depletion', pos: 'n.', def: 'the reduction of a resource to a critically low level', ex: 'Aquifer depletion threatens future agricultural productivity in the region.', col: 'resource depletion' },
      { term: 'precipitation', pos: 'n.', def: 'rain, snow, or other moisture falling from the atmosphere', ex: 'Shifting precipitation patterns disrupt traditional farming calendars.', col: 'annual precipitation' },
      { term: 'erosion', pos: 'n.', def: 'the gradual wearing away of soil or rock by natural forces', ex: 'Coastal erosion has forced several communities to relocate key infrastructure.', col: 'soil erosion' },
      { term: 'watershed', pos: 'n.', def: 'an area of land that drains into a particular river or lake', ex: 'Effective watershed management requires cooperation across political boundaries.', col: 'watershed protection' },
      { term: 'flora', pos: 'n.', def: 'the plant life characteristic of a particular region', ex: 'Regional flora adapts slowly to abrupt changes in temperature and rainfall.', col: 'native flora' },
      { term: 'fauna', pos: 'n.', def: 'the animal life characteristic of a particular region', ex: 'Invasive predators have destabilised local fauna on several islands.', col: 'indigenous fauna' },
      { term: 'aquifer', pos: 'n.', def: 'an underground layer of rock that holds groundwater', ex: 'Excessive pumping has depleted the region\'s primary aquifer within decades.', col: 'aquifer recharge' },
      { term: 'biodegradable', pos: 'adj.', def: 'capable of being broken down naturally by living organisms', ex: 'Retailers increasingly favour biodegradable packaging to cut landfill waste.', col: 'biodegradable materials' },
      { term: 'ecotourism', pos: 'n.', def: 'low-impact tourism that supports conservation of natural areas', ex: 'Well-regulated ecotourism can fund habitat restoration without harming wildlife.', col: 'sustainable ecotourism' },
      { term: 'runoff', pos: 'n.', def: 'water that flows over land into streams, often carrying pollutants', ex: 'Agricultural runoff carries excess fertiliser into nearby rivers and lakes.', col: 'surface runoff' },
      { term: 'landfill', pos: 'n.', def: 'a site where waste is buried under layers of earth', ex: 'Methane from landfills contributes significantly to national greenhouse inventories.', col: 'municipal landfill' },
      { term: 'scarcity', pos: 'n.', def: 'a situation in which a resource is insufficient to meet demand', ex: 'Water scarcity intensifies diplomatic tension among neighbouring states.', col: 'resource scarcity' },
      { term: 'anthropogenic', pos: 'adj.', def: 'caused or influenced by human activity', ex: 'Scientists agree that recent warming is predominantly anthropogenic in origin.', col: 'anthropogenic emissions' },
      { term: 'acidification', pos: 'n.', def: 'the process of becoming more acidic', ex: 'Ocean acidification weakens shells in organisms at the base of marine food webs.', col: 'ocean acidification' },
      { term: 'reforestation', pos: 'n.', def: 'the deliberate restoration of forest cover on cleared land', ex: 'Large-scale reforestation projects sequester carbon while rebuilding habitat.', col: 'reforestation programme' },
      { term: 'invasive', pos: 'adj.', def: 'describing a non-native species that harms local ecosystems', ex: 'Invasive plants outcompete endemic species and alter fire regimes.', col: 'invasive species' },
      { term: 'ozone', pos: 'n.', def: 'a form of oxygen in the atmosphere that blocks ultraviolet radiation', ex: 'The ozone layer shields terrestrial life from harmful solar radiation.', col: 'ozone layer' },
      { term: 'particulate', pos: 'n.', def: 'microscopic solid or liquid particles suspended in air', ex: 'Fine particulate matter penetrates deep into the lungs and bloodstream.', col: 'fine particulate matter' },
      { term: 'tipping point', pos: 'n.', def: 'a threshold beyond which change becomes difficult to reverse', ex: 'Researchers warn that several climatic tipping points may be approached this century.', col: 'ecological tipping point' },
      { term: 'stewardship', pos: 'n.', def: 'responsible care and management of the natural world', ex: 'Environmental stewardship should be taught as a civic duty in schools.', col: 'land stewardship' },
      { term: 'decarbonise', pos: 'v.', def: 'to reduce or eliminate carbon emissions from a sector or economy', ex: 'Several nations aim to decarbonise their power grids by mid-century.', col: 'decarbonise the economy' },
      { term: 'monoculture', pos: 'n.', def: 'the cultivation of a single crop over a large area', ex: 'Agricultural monoculture depletes soil nutrients and increases pest vulnerability.', col: 'crop monoculture' },
      { term: 'sequestration', pos: 'n.', def: 'the long-term storage of carbon dioxide away from the atmosphere', ex: 'Forest carbon sequestration offers a cost-effective mitigation strategy.', col: 'carbon sequestration' },
      { term: 'biodigestion', pos: 'n.', def: 'the breakdown of organic waste by microorganisms to produce energy', ex: 'Farm biodigestion converts manure into biogas while reducing methane releases.', col: 'anaerobic biodigestion' },
      { term: 'eutrophication', pos: 'n.', def: 'excessive nutrient enrichment that depletes oxygen in water bodies', ex: 'Lake eutrophication followed decades of untreated sewage discharge upstream.', col: 'cultural eutrophication' },
      { term: 'permafrost', pos: 'n.', def: 'ground that remains frozen for two or more consecutive years', ex: 'Thawing permafrost releases stored methane and destabilises Arctic infrastructure.', col: 'permafrost thaw' },
      { term: 'afforestation', pos: 'n.', def: 'the establishment of forest on land that was not previously forested', ex: 'National afforestation targets aim to offset emissions from transport.', col: 'afforestation project' },
      { term: 'bioaccumulation', pos: 'n.', def: 'the gradual buildup of toxins in organisms through the food chain', ex: 'Mercury bioaccumulation in fish poses risks to coastal communities.', col: 'bioaccumulation of toxins' },
      { term: 'remediation', pos: 'n.', def: 'the process of reversing environmental damage or contamination', ex: 'Soil remediation at the former factory site took nearly five years.', col: 'environmental remediation' },
      { term: 'photovoltaic', pos: 'adj.', def: 'relating to technology that converts sunlight directly into electricity', ex: 'Photovoltaic panels now supply a growing share of household electricity.', col: 'photovoltaic system' },
      { term: 'composting', pos: 'n.', def: 'the controlled decomposition of organic waste into fertile soil amendment', ex: 'Municipal composting programmes divert food waste from incineration.', col: 'organic composting' },
      { term: 'overfishing', pos: 'n.', def: 'harvesting fish stocks faster than they can naturally replenish', ex: 'Overfishing has collapsed several commercially important fisheries worldwide.', col: 'prevent overfishing' },
      { term: 'xeriscaping', pos: 'n.', def: 'landscaping designed to minimise water use in dry climates', ex: 'Xeriscaping reduced municipal irrigation demand during prolonged droughts.', col: 'xeriscape design' },
      { term: 'greenwashing', pos: 'n.', def: 'misleading marketing that exaggerates a product\'s environmental benefits', ex: 'Regulators are cracking down on greenwashing in the fashion industry.', col: 'accused of greenwashing' },
      { term: 'resilience', pos: 'n.', def: 'the capacity of ecosystems or communities to recover from disturbance', ex: 'Coastal resilience planning combines wetlands restoration with early warning systems.', col: 'ecological resilience' },
      { term: 'transboundary', pos: 'adj.', def: 'crossing or shared between national borders', ex: 'Transboundary pollution requires treaties stronger than domestic regulation alone.', col: 'transboundary river' },
      { term: 'net zero', pos: 'phr.', def: 'the balance between greenhouse gases emitted and removed', ex: 'The corporation pledged to reach net zero across its supply chain by 2040.', col: 'achieve net zero' }
    ]
  },
  {
    topic: 'Technology',
    words: [
      { term: 'algorithm', pos: 'n.', def: 'a step-by-step set of rules used to solve a problem or process data', ex: 'Recommendation algorithms shape what millions of users see online each day.', col: 'machine-learning algorithm' },
      { term: 'automation', pos: 'n.', def: 'the use of technology to perform tasks with minimal human input', ex: 'Factory automation has raised productivity but displaced some manual roles.', col: 'process automation' },
      { term: 'bandwidth', pos: 'n.', def: 'the capacity of a network to transmit data in a given time', ex: 'Rural schools often lack the bandwidth needed for reliable video lessons.', col: 'high bandwidth' },
      { term: 'cybersecurity', pos: 'n.', def: 'measures to protect systems and data from digital attacks', ex: 'Cybersecurity spending rose after several hospitals suffered ransomware breaches.', col: 'cybersecurity framework' },
      { term: 'digitisation', pos: 'n.', def: 'the conversion of information or processes into digital form', ex: 'Digitisation of medical records improved access but raised privacy concerns.', col: 'rapid digitisation' },
      { term: 'encryption', pos: 'n.', def: 'the encoding of data so only authorised parties can read it', ex: 'End-to-end encryption protects messages from interception on public networks.', col: 'data encryption' },
      { term: 'prototype', pos: 'n.', def: 'an early model used to test a design before full production', ex: 'Engineers refined the prototype after user trials revealed interface flaws.', col: 'working prototype' },
      { term: 'scalable', pos: 'adj.', def: 'able to grow in capacity without proportional loss of performance', ex: 'Cloud platforms offer scalable storage for startups with unpredictable demand.', col: 'scalable solution' },
      { term: 'interface', pos: 'n.', def: 'the point at which a user interacts with a device or program', ex: 'A cluttered interface discourages older adults from adopting mobile banking.', col: 'user interface' },
      { term: 'latency', pos: 'n.', def: 'the delay between a request and a response in a system', ex: 'Low latency is essential for real-time surgical robotics and gaming.', col: 'network latency' },
      { term: 'blockchain', pos: 'n.', def: 'a distributed ledger that records transactions across many computers', ex: 'Blockchain applications extend beyond cryptocurrency into supply-chain tracking.', col: 'blockchain technology' },
      { term: 'artificial intelligence', pos: 'n.', def: 'computer systems that perform tasks requiring human-like reasoning', ex: 'Artificial intelligence assists radiologists but cannot replace clinical judgment.', col: 'artificial intelligence research' },
      { term: 'connectivity', pos: 'n.', def: 'the state of being linked to a network or other devices', ex: 'Universal connectivity remains elusive in remote mountainous regions.', col: 'internet connectivity' },
      { term: 'disruptive', pos: 'adj.', def: 'describing innovation that fundamentally changes an established industry', ex: 'Disruptive technologies can render incumbent business models obsolete within years.', col: 'disruptive innovation' },
      { term: 'firmware', pos: 'n.', def: 'permanent software programmed into hardware devices', ex: 'A firmware update patched the vulnerability affecting millions of routers.', col: 'install firmware' },
      { term: 'geolocation', pos: 'n.', def: 'the identification of a device\'s physical position using digital signals', ex: 'Geolocation data from apps raises questions about consent and surveillance.', col: 'geolocation services' },
      { term: 'hardware', pos: 'n.', def: 'the physical components of a computer or electronic system', ex: 'Obsolete hardware increases e-waste unless manufacturers design for repair.', col: 'computer hardware' },
      { term: 'iteration', pos: 'n.', def: 'a repeated version of a product or process refined over time', ex: 'Each software iteration addressed bugs reported by beta testers.', col: 'design iteration' },
      { term: 'malware', pos: 'n.', def: 'software designed to damage or gain unauthorised access to systems', ex: 'Employees opened phishing emails that installed malware on corporate servers.', col: 'detect malware' },
      { term: 'metadata', pos: 'n.', def: 'data that describes other data, such as author, date, or format', ex: 'Photo metadata can reveal location even when the image is anonymised.', col: 'extract metadata' },
      { term: 'open source', pos: 'adj.', def: 'software whose code is publicly available for modification and reuse', ex: 'Open source tools lowered barriers for researchers in developing countries.', col: 'open-source community' },
      { term: 'peripheral', pos: 'n.', def: 'an external device connected to a computer, such as a printer', ex: 'Wireless peripherals reduce cable clutter in modern office setups.', col: 'peripheral device' },
      { term: 'quantum computing', pos: 'n.', def: 'computation using quantum-mechanical phenomena to process information', ex: 'Quantum computing may eventually break current cryptographic standards.', col: 'quantum computing research' },
      { term: 'redundancy', pos: 'n.', def: 'duplicate components that keep a system running if one fails', ex: 'Data centres build redundancy into power and cooling infrastructure.', col: 'system redundancy' },
      { term: 'semiconductor', pos: 'n.', def: 'a material that conducts electricity under specific conditions, used in chips', ex: 'Global semiconductor shortages delayed vehicle production for months.', col: 'semiconductor industry' },
      { term: 'telemetry', pos: 'n.', def: 'the automatic transmission of measurements from remote equipment', ex: 'Satellite telemetry helps scientists monitor glacier retreat in real time.', col: 'telemetry data' },
      { term: 'ubiquitous', pos: 'adj.', def: 'present or found everywhere', ex: 'Smartphones have made mobile internet access ubiquitous in urban life.', col: 'ubiquitous computing' },
      { term: 'virtualisation', pos: 'n.', def: 'creating a virtual version of hardware, storage, or networks', ex: 'Server virtualisation cut energy use by consolidating underused machines.', col: 'hardware virtualisation' },
      { term: 'wearable', pos: 'n.', def: 'a small electronic device worn on the body to track health or activity', ex: 'Wearables encourage users to monitor sleep but may overstate accuracy.', col: 'wearable technology' },
      { term: 'zero-day', pos: 'n.', def: 'a software vulnerability unknown to the vendor and unpatched', ex: 'Nation-state actors exploited a zero-day flaw before a patch was released.', col: 'zero-day exploit' },
      { term: 'biometrics', pos: 'n.', def: 'identification using unique physical traits such as fingerprints', ex: 'Airport biometrics speed boarding yet intensify debates over privacy.', col: 'biometric authentication' },
      { term: 'cache', pos: 'n.', def: 'temporary storage that speeds up repeated access to data', ex: 'Clearing the browser cache often resolves outdated page display issues.', col: 'cache memory' },
      { term: 'decentralised', pos: 'adj.', def: 'distributed across many nodes rather than controlled centrally', ex: 'Decentralised networks resist single points of failure during outages.', col: 'decentralised system' },
      { term: 'ergonomic', pos: 'adj.', def: 'designed for efficiency and comfort in human use', ex: 'Ergonomic keyboards reduce strain for staff who type eight hours daily.', col: 'ergonomic design' },
      { term: 'fibre-optic', pos: 'adj.', def: 'using thin glass fibres to transmit data as light signals', ex: 'Fibre-optic cables deliver far higher speeds than traditional copper lines.', col: 'fibre-optic network' },
      { term: 'gamification', pos: 'n.', def: 'applying game-like elements to non-game tasks to increase engagement', ex: 'Gamification in language apps motivates learners through points and streaks.', col: 'gamification strategy' },
      { term: 'haptic', pos: 'adj.', def: 'relating to technology that simulates touch through force or vibration', ex: 'Haptic feedback in surgical simulators trains dexterity without patient risk.', col: 'haptic interface' },
      { term: 'interoperability', pos: 'n.', def: 'the ability of different systems to work together seamlessly', ex: 'Healthcare interoperability allows clinics to share records across platforms.', col: 'ensure interoperability' },
      { term: 'jurisdiction', pos: 'n.', def: 'the legal authority of a state over online activity within its borders', ex: 'Cross-border data flows complicate jurisdiction over tech companies.', col: 'legal jurisdiction' },
      { term: 'kernel', pos: 'n.', def: 'the core component of an operating system managing hardware resources', ex: 'A flaw in the kernel affected security patches across several Linux distributions.', col: 'operating-system kernel' },
      { term: 'legacy system', pos: 'n.', def: 'outdated technology still in use because migration is costly', ex: 'Banks rely on legacy systems that are expensive to replace but risky to keep.', col: 'upgrade legacy systems' },
      { term: 'microprocessor', pos: 'n.', def: 'an integrated circuit that performs the functions of a central processing unit', ex: 'Advances in microprocessor design drove exponential growth in computing power.', col: 'microprocessor chip' },
      { term: 'nanotechnology', pos: 'n.', def: 'the manipulation of matter at molecular or atomic scale', ex: 'Nanotechnology enables targeted drug delivery with fewer side effects.', col: 'nanotechnology applications' },
      { term: 'optical character recognition', pos: 'n.', def: 'technology that converts scanned text images into editable digital text', ex: 'Optical character recognition digitised archives of historical newspapers.', col: 'OCR software' },
      { term: 'phishing', pos: 'n.', def: 'fraudulent attempts to obtain sensitive data by impersonating trusted senders', ex: 'Staff training reduced successful phishing attacks within the organisation.', col: 'phishing scam' },
      { term: 'query', pos: 'n.', def: 'a request for information from a database or search engine', ex: 'Poorly formed database queries can slow applications during peak traffic.', col: 'run a query' },
      { term: 'render', pos: 'v.', def: 'to generate a visual image or output from digital data', ex: 'The studio needs powerful GPUs to render complex three-dimensional scenes.', col: 'render graphics' },
      { term: 'throughput', pos: 'n.', def: 'the amount of data processed by a system in a given period', ex: 'Network upgrades doubled throughput during peak e-commerce seasons.', col: 'maximise throughput' },
      { term: 'uptime', pos: 'n.', def: 'the period during which a system remains operational and available', ex: 'Cloud providers guarantee uptime in service-level agreements with penalties.', col: 'system uptime' },
      { term: 'vulnerability', pos: 'n.', def: 'a weakness in software or hardware that can be exploited', ex: 'Researchers disclosed the vulnerability responsibly before public exploit code spread.', col: 'security vulnerability' }
    ]
  },
  {
    topic: 'Education',
    words: [
      { term: 'curriculum', pos: 'n.', def: 'the subjects and content taught in a school or course', ex: 'The national curriculum now includes digital literacy from primary level.', col: 'school curriculum' },
      { term: 'pedagogy', pos: 'n.', def: 'the methods and theory of teaching', ex: 'Effective pedagogy balances direct instruction with collaborative inquiry.', col: 'modern pedagogy' },
      { term: 'literacy', pos: 'n.', def: 'the ability to read, write, and understand written information', ex: 'Adult literacy programmes reduced unemployment in several rural counties.', col: 'literacy rate' },
      { term: 'enrolment', pos: 'n.', def: 'the act of registering as a student at an institution', ex: 'University enrolment surged after tuition fees were partially subsidised.', col: 'student enrolment' },
      { term: 'assessment', pos: 'n.', def: 'the evaluation of a student\'s knowledge or skills', ex: 'Formative assessment helps teachers adjust lessons before final examinations.', col: 'continuous assessment' },
      { term: 'accreditation', pos: 'n.', def: 'official recognition that an institution meets required standards', ex: 'Loss of accreditation would prevent graduates from practising medicine legally.', col: 'gain accreditation' },
      { term: 'dissertation', pos: 'n.', def: 'a long research paper submitted for an advanced degree', ex: 'She defended her dissertation on inclusive education policy in urban schools.', col: 'doctoral dissertation' },
      { term: 'extracurricular', pos: 'adj.', def: 'activities outside the standard academic timetable', ex: 'Extracurricular clubs develop leadership skills not always measured in tests.', col: 'extracurricular activity' },
      { term: 'plagiarism', pos: 'n.', def: 'presenting another person\'s work as one\'s own without attribution', ex: 'Universities use software to detect plagiarism in submitted essays.', col: 'commit plagiarism' },
      { term: 'scholarship', pos: 'n.', def: 'financial aid awarded for academic achievement or need', ex: 'Merit-based scholarships attract talented students from low-income backgrounds.', col: 'full scholarship' },
      { term: 'vocational', pos: 'adj.', def: 'relating to training for a specific trade or occupation', ex: 'Vocational colleges address skills gaps that universities sometimes overlook.', col: 'vocational training' },
      { term: 'syllabus', pos: 'n.', def: 'an outline of topics covered in a particular course', ex: 'The revised syllabus places greater emphasis on critical thinking tasks.', col: 'course syllabus' },
      { term: 'tuition', pos: 'n.', def: 'the fee charged for instruction at a school or university', ex: 'Rising tuition has prompted debate over who should fund higher education.', col: 'tuition fees' },
      { term: 'mentorship', pos: 'n.', def: 'guidance provided by an experienced person to a learner', ex: 'Faculty mentorship improved retention among first-generation undergraduates.', col: 'mentorship programme' },
      { term: 'remedial', pos: 'adj.', def: 'intended to correct basic deficiencies in learning', ex: 'Remedial classes in mathematics prepared students for mainstream engineering courses.', col: 'remedial education' },
      { term: 'cognitive', pos: 'adj.', def: 'relating to mental processes such as thinking and memory', ex: 'Cognitive load theory explains why overloaded slides hinder comprehension.', col: 'cognitive development' },
      { term: 'compulsory', pos: 'adj.', def: 'required by law or rule', ex: 'Compulsory schooling until sixteen reduced child labour in the region.', col: 'compulsory education' },
      { term: 'doctoral', pos: 'adj.', def: 'relating to the highest university degree, usually by research', ex: 'Doctoral candidates must publish original findings in peer-reviewed journals.', col: 'doctoral programme' },
      { term: 'equity', pos: 'n.', def: 'fair access to opportunities regardless of background', ex: 'Education equity policies target funding toward under-resourced districts.', col: 'educational equity' },
      { term: 'faculty', pos: 'n.', def: 'the teaching staff of a university or college', ex: 'The faculty voted to adopt blended learning after the pilot semester.', col: 'faculty member' },
      { term: 'holistic', pos: 'adj.', def: 'considering the whole person rather than isolated skills', ex: 'Holistic admissions review personal statements alongside examination scores.', col: 'holistic approach' },
      { term: 'inclusive', pos: 'adj.', def: 'designed so all learners, including those with disabilities, can participate', ex: 'Inclusive classrooms adapt materials for students with diverse needs.', col: 'inclusive education' },
      { term: 'jargon', pos: 'n.', def: 'specialised language that may confuse non-specialists', ex: 'Academic jargon in lectures can alienate students new to the discipline.', col: 'technical jargon' },
      { term: 'kindergarten', pos: 'n.', def: 'school or class for children before primary education', ex: 'Early kindergarten attendance correlates with stronger literacy in grade three.', col: 'attend kindergarten' },
      { term: 'lecture', pos: 'n.', def: 'a formal talk given to students, often to a large group', ex: 'Recorded lectures allow revision but may reduce live classroom discussion.', col: 'attend a lecture' },
      { term: 'matriculation', pos: 'n.', def: 'formal admission to a university or the ceremony marking it', ex: 'Matriculation requirements include both language proficiency and science credits.', col: 'matriculation examination' },
      { term: 'numeracy', pos: 'n.', def: 'the ability to understand and work with numbers', ex: 'Workplace numeracy training improved accuracy in inventory management roles.', col: 'basic numeracy' },
      { term: 'orientation', pos: 'n.', def: 'an introductory programme for new students or staff', ex: 'Week-long orientation helped international students navigate campus services.', col: 'student orientation' },
      { term: 'proficiency', pos: 'n.', def: 'a high degree of competence in a skill or language', ex: 'Employers increasingly demand proficiency in English for global roles.', col: 'language proficiency' },
      { term: 'qualification', pos: 'n.', def: 'a certificate or diploma showing completion of a course of study', ex: 'Professional qualifications must be renewed through continuing education credits.', col: 'academic qualification' },
      { term: 'rubric', pos: 'n.', def: 'a scoring guide listing criteria for assessing student work', ex: 'A clear rubric reduces subjective grading in extended writing tasks.', col: 'assessment rubric' },
      { term: 'semester', pos: 'n.', def: 'half of an academic year', ex: 'Exchange students typically spend one semester abroad before graduating.', col: 'fall semester' },
      { term: 'tenure', pos: 'n.', def: 'permanent appointment granted to senior academics after review', ex: 'The tenure process evaluates research output, teaching, and service equally.', col: 'grant tenure' },
      { term: 'undergraduate', pos: 'n.', def: 'a student pursuing a first university degree', ex: 'Undergraduates benefit from research internships usually reserved for graduates.', col: 'undergraduate degree' },
      { term: 'validity', pos: 'n.', def: 'the extent to which a test measures what it claims to measure', ex: 'Experts questioned the validity of high-stakes exams after curriculum reform.', col: 'test validity' },
      { term: 'workshop', pos: 'n.', def: 'a practical session focused on active skill development', ex: 'The writing workshop improved thesis structure through peer feedback.', col: 'interactive workshop' },
      { term: 'bilingual', pos: 'adj.', def: 'fluent in two languages', ex: 'Bilingual education models strengthen heritage languages without harming English scores.', col: 'bilingual schooling' },
      { term: 'cramming', pos: 'n.', def: 'intensive last-minute study before an examination', ex: 'Cramming may raise short-term scores but undermines long-term retention.', col: 'exam cramming' },
      { term: 'dropout', pos: 'n.', def: 'a student who leaves school before completing a programme', ex: 'Mentoring programmes lowered the dropout rate among at-risk adolescents.', col: 'school dropout' },
      { term: 'edtech', pos: 'n.', def: 'technology designed to support teaching and learning', ex: 'Edtech adoption accelerated when campuses closed during the pandemic.', col: 'edtech platform' },
      { term: 'flipped classroom', pos: 'n.', def: 'a model where students study content at home and practise in class', ex: 'The flipped classroom freed class time for problem-solving discussions.', col: 'flipped classroom model' },
      { term: 'grant', pos: 'n.', def: 'funding awarded for research or educational projects', ex: 'The laboratory secured a grant to study bilingual reading development.', col: 'research grant' },
      { term: 'homework', pos: 'n.', def: 'tasks assigned to be completed outside class time', ex: 'Excessive homework can reduce sleep and family time for younger pupils.', col: 'assign homework' },
      { term: 'inquiry-based', pos: 'adj.', def: 'learning driven by student questions and investigation', ex: 'Inquiry-based science lessons improved engagement more than textbook drills.', col: 'inquiry-based learning' },
      { term: 'juvenile', pos: 'adj.', def: 'relating to children or young people', ex: 'Juvenile justice reforms emphasise education over punitive detention.', col: 'juvenile offender' },
      { term: 'kinaesthetic', pos: 'adj.', def: 'relating to learning through physical movement and touch', ex: 'Kinaesthetic activities help pupils who struggle with purely auditory instruction.', col: 'kinaesthetic learner' },
      { term: 'lifelong learning', pos: 'n.', def: 'continuing education throughout adulthood', ex: 'Lifelong learning policies support workers displaced by automation.', col: 'promote lifelong learning' },
      { term: 'MOOC', pos: 'n.', def: 'a massive open online course available to unlimited enrolment', ex: 'MOOCs democratise access to elite lectures but completion rates remain low.', col: 'enrol in a MOOC' },
      { term: 'pedantic', pos: 'adj.', def: 'overly concerned with minor rules or formal detail', ex: 'Pedantic marking of spelling can discourage risk-taking in creative writing.', col: 'pedantic correction' },
      { term: 'streaming', pos: 'n.', def: 'grouping students by perceived ability within a subject', ex: 'Streaming in mathematics widened achievement gaps according to longitudinal data.', col: 'ability streaming' }
    ]
  },
  {
    topic: 'Health',
    words: [
      { term: 'epidemiology', pos: 'n.', def: 'the study of how diseases spread and affect populations', ex: 'Epidemiology traced the outbreak to contaminated water supplies upstream.', col: 'field epidemiology' },
      { term: 'immunisation', pos: 'n.', def: 'the process of making a person immune to a disease, often by vaccine', ex: 'Childhood immunisation programmes eradicated polio in most regions.', col: 'routine immunisation' },
      { term: 'prognosis', pos: 'n.', def: 'the likely course and outcome of a disease', ex: 'Early detection improved the prognosis for patients with breast cancer.', col: 'favourable prognosis' },
      { term: 'chronic', pos: 'adj.', def: 'persisting for a long time or constantly recurring', ex: 'Chronic conditions such as diabetes strain national healthcare budgets.', col: 'chronic disease' },
      { term: 'acute', pos: 'adj.', def: 'severe and sudden in onset', ex: 'Acute respiratory failure required immediate transfer to intensive care.', col: 'acute symptoms' },
      { term: 'comorbidity', pos: 'n.', def: 'the presence of two or more conditions in the same patient', ex: 'Comorbidity between obesity and hypertension complicates treatment plans.', col: 'multiple comorbidity' },
      { term: 'pathogen', pos: 'n.', def: 'a microorganism that causes disease', ex: 'The pathogen resisted several antibiotics commonly used in hospitals.', col: 'bacterial pathogen' },
      { term: 'symptom', pos: 'n.', def: 'a physical or mental sign indicating illness', ex: 'Fever is a common symptom of viral infections in young children.', col: 'present symptoms' },
      { term: 'diagnosis', pos: 'n.', def: 'identification of a disease from its signs and tests', ex: 'Delayed diagnosis allowed the infection to spread within the ward.', col: 'accurate diagnosis' },
      { term: 'rehabilitation', pos: 'n.', def: 'therapy to restore function after injury or illness', ex: 'Stroke rehabilitation improved mobility through daily physiotherapy sessions.', col: 'cardiac rehabilitation' },
      { term: 'preventive', pos: 'adj.', def: 'intended to stop disease before it occurs', ex: 'Preventive screening programmes detect cancers at more treatable stages.', col: 'preventive medicine' },
      { term: 'palliative', pos: 'adj.', def: 'relieving pain without aiming to cure the underlying disease', ex: 'Palliative care teams support dignity for terminally ill patients at home.', col: 'palliative care' },
      { term: 'antibiotic', pos: 'n.', def: 'a drug that kills or inhibits bacteria', ex: 'Overuse of antibiotics accelerates resistance in common pathogens.', col: 'prescribe antibiotics' },
      { term: 'metabolism', pos: 'n.', def: 'chemical processes in the body that maintain life', ex: 'Thyroid disorders disrupt metabolism and cause unexplained weight change.', col: 'basal metabolism' },
      { term: 'hypertension', pos: 'n.', def: 'persistently high blood pressure', ex: 'Hypertension remains a leading risk factor for stroke worldwide.', col: 'treat hypertension' },
      { term: 'malnutrition', pos: 'n.', def: 'deficiency or imbalance of nutrients affecting health', ex: 'Malnutrition in infants can cause irreversible cognitive impairment.', col: 'severe malnutrition' },
      { term: 'obesity', pos: 'n.', def: 'excess body fat that increases risk of disease', ex: 'Obesity rates among adolescents have risen alongside sugary drink consumption.', col: 'childhood obesity' },
      { term: 'trauma', pos: 'n.', def: 'a serious physical injury, often from accident or violence', ex: 'Emergency departments prioritise trauma cases requiring immediate surgery.', col: 'blunt trauma' },
      { term: 'sterile', pos: 'adj.', def: 'free from living microorganisms', ex: 'Surgeons operate in sterile environments to minimise postoperative infection.', col: 'sterile equipment' },
      { term: 'dosage', pos: 'n.', def: 'the amount of medicine taken at one time or over a period', ex: 'Incorrect dosage of insulin can cause dangerous hypoglycaemia.', col: 'correct dosage' },
      { term: 'contagious', pos: 'adj.', def: 'able to spread from one person to another', ex: 'Highly contagious variants prompted renewed mask mandates in transit hubs.', col: 'contagious disease' },
      { term: 'hereditary', pos: 'adj.', def: 'passed from parents to offspring through genes', ex: 'Hereditary factors interact with diet in many cardiovascular conditions.', col: 'hereditary condition' },
      { term: 'inpatient', pos: 'n.', def: 'a patient who stays in hospital for treatment', ex: 'Inpatient beds filled rapidly during the seasonal influenza surge.', col: 'inpatient care' },
      { term: 'outpatient', pos: 'n.', def: 'a patient who receives treatment without staying overnight', ex: 'Outpatient clinics reduced pressure on emergency departments for minor cases.', col: 'outpatient service' },
      { term: 'sedentary', pos: 'adj.', def: 'involving little physical activity', ex: 'Sedentary office work contributes to musculoskeletal pain and weight gain.', col: 'sedentary lifestyle' },
      { term: 'therapeutic', pos: 'adj.', def: 'relating to healing or treatment of disease', ex: 'Therapeutic exercise programmes eased chronic lower back pain.', col: 'therapeutic intervention' },
      { term: 'vaccine', pos: 'n.', def: 'a substance that stimulates immunity to a specific disease', ex: 'The new vaccine showed strong efficacy in large phase-three trials.', col: 'vaccine rollout' },
      { term: 'wellness', pos: 'n.', def: 'the active pursuit of physical and mental well-being', ex: 'Corporate wellness initiatives include stress management and fitness subsidies.', col: 'health and wellness' },
      { term: 'anxiety', pos: 'n.', def: 'a condition of persistent worry that can impair daily functioning', ex: 'Untreated anxiety in students correlates with poorer academic performance.', col: 'generalised anxiety' },
      { term: 'depression', pos: 'n.', def: 'a mood disorder involving prolonged sadness and loss of interest', ex: 'Primary care physicians increasingly screen for depression during check-ups.', col: 'clinical depression' },
      { term: 'resilience', pos: 'n.', def: 'the ability to recover mentally from adversity', ex: 'Community programmes build psychological resilience after natural disasters.', col: 'mental resilience' },
      { term: 'stigma', pos: 'n.', def: 'social disapproval that discourages people from seeking help', ex: 'Stigma around mental illness prevents many from accessing counselling.', col: 'social stigma' },
      { term: 'telemedicine', pos: 'n.', def: 'remote delivery of healthcare using digital communication', ex: 'Telemedicine expanded access for rural patients with limited transport.', col: 'telemedicine consultation' },
      { term: 'biomarker', pos: 'n.', def: 'a measurable indicator of a biological state or condition', ex: 'Blood biomarkers may detect Alzheimer\'s years before symptoms appear.', col: 'diagnostic biomarker' },
      { term: 'clinical trial', pos: 'n.', def: 'a research study testing new treatments on human volunteers', ex: 'The clinical trial was halted when adverse effects exceeded safety thresholds.', col: 'phase-three clinical trial' },
      { term: 'epidemic', pos: 'n.', def: 'a widespread occurrence of disease in a community at one time', ex: 'Authorities declared an epidemic after cases doubled within two weeks.', col: 'contain an epidemic' },
      { term: 'pandemic', pos: 'n.', def: 'an epidemic occurring over a very wide geographic area', ex: 'The pandemic exposed weaknesses in global supply chains for protective equipment.', col: 'global pandemic' },
      { term: 'quarantine', pos: 'n.', def: 'isolation to prevent spread of contagious disease', ex: 'Travellers completed quarantine before returning to frontline healthcare roles.', col: 'mandatory quarantine' },
      { term: 'sanitation', pos: 'n.', def: 'conditions and practices that promote hygiene and prevent disease', ex: 'Improved sanitation cut diarrhoeal deaths in low-income neighbourhoods.', col: 'sanitation facilities' },
      { term: 'triage', pos: 'n.', def: 'prioritising patients by urgency when resources are limited', ex: 'Nurses performed triage in the car park during the mass-casualty incident.', col: 'emergency triage' },
      { term: 'anaesthesia', pos: 'n.', def: 'loss of sensation induced for surgical procedures', ex: 'Regional anaesthesia allowed the patient to remain conscious yet pain-free.', col: 'general anaesthesia' },
      { term: 'congenital', pos: 'adj.', def: 'present from birth, often due to genetic factors', ex: 'Congenital heart defects require monitoring from infancy through adulthood.', col: 'congenital abnormality' },
      { term: 'detoxification', pos: 'n.', def: 'medical supervision while clearing addictive substances from the body', ex: 'Detoxification alone rarely succeeds without long-term counselling support.', col: 'medical detoxification' },
      { term: 'epigenetic', pos: 'adj.', def: 'relating to changes in gene expression not caused by DNA sequence', ex: 'Epigenetic research links early stress to adult susceptibility to illness.', col: 'epigenetic mechanism' },
      { term: 'frailty', pos: 'n.', def: 'physical vulnerability and reduced reserve in older adults', ex: 'Frailty assessments guide whether elderly patients can tolerate aggressive chemotherapy.', col: 'age-related frailty' },
      { term: 'gene therapy', pos: 'n.', def: 'treatment that modifies genes to correct or fight disease', ex: 'Gene therapy offers hope for inherited disorders once deemed untreatable.', col: 'gene therapy trial' },
      { term: 'holistic', pos: 'adj.', def: 'treating the whole person including mental and social factors', ex: 'Holistic health programmes combine nutrition counselling with stress reduction.', col: 'holistic health' },
      { term: 'incidence', pos: 'n.', def: 'the rate at which new cases of a disease occur', ex: 'Incidence of type-two diabetes rose among sedentary office workers.', col: 'disease incidence' },
      { term: 'placebo', pos: 'n.', def: 'an inactive treatment given to control for psychological effects', ex: 'The placebo group reported improvement, illustrating the mind-body connection.', col: 'placebo effect' },
      { term: 'remission', pos: 'n.', def: 'a period when symptoms of disease lessen or disappear', ex: 'The patient remained in remission five years after completing chemotherapy.', col: 'achieve remission' }
    ]
  },
  {
    topic: 'Society',
    words: [
      { term: 'inequality', pos: 'n.', def: 'unequal distribution of resources, rights, or opportunities', ex: 'Income inequality widened despite overall economic growth last decade.', col: 'social inequality' },
      { term: 'demographic', pos: 'adj.', def: 'relating to the structure and statistics of a population', ex: 'Demographic ageing will strain pension systems in many OECD nations.', col: 'demographic shift' },
      { term: 'assimilation', pos: 'n.', def: 'the process by which minority groups adopt dominant cultural norms', ex: 'Forced assimilation policies erased indigenous languages within two generations.', col: 'cultural assimilation' },
      { term: 'civic', pos: 'adj.', def: 'relating to the duties and rights of citizens in a community', ex: 'Civic education encourages voting and informed participation in local government.', col: 'civic engagement' },
      { term: 'cohesion', pos: 'n.', def: 'the bonds that unite members of a society', ex: 'Volunteer networks strengthened social cohesion after the flood disaster.', col: 'social cohesion' },
      { term: 'discrimination', pos: 'n.', def: 'unfair treatment based on group membership such as race or gender', ex: 'Workplace discrimination persists despite equal-opportunity legislation.', col: 'racial discrimination' },
      { term: 'gentrification', pos: 'n.', def: 'renovation of poor urban areas that displaces original residents', ex: 'Gentrification raised property values but priced out long-term tenants.', col: 'urban gentrification' },
      { term: 'marginalised', pos: 'adj.', def: 'placed at the edge of society with limited power or voice', ex: 'Policies must address the needs of marginalised rural communities.', col: 'marginalised groups' },
      { term: 'pluralism', pos: 'n.', def: 'a society that recognises and tolerates diverse beliefs and groups', ex: 'Religious pluralism flourished where constitutions guaranteed freedom of worship.', col: 'cultural pluralism' },
      { term: 'segregation', pos: 'n.', def: 'the enforced separation of groups in housing, schools, or public life', ex: 'Residential segregation still maps onto disparities in school funding.', col: 'racial segregation' },
      { term: 'urbanisation', pos: 'n.', def: 'the growth of cities as people move from rural areas', ex: 'Rapid urbanisation outpaced investment in affordable housing and transit.', col: 'rapid urbanisation' },
      { term: 'welfare', pos: 'n.', def: 'government support for citizens in financial or social need', ex: 'Welfare reforms aimed to reduce poverty traps while controlling public spending.', col: 'welfare state' },
      { term: 'activism', pos: 'n.', def: 'vigorous campaigning for political or social change', ex: 'Youth activism pushed legislatures to adopt stricter climate targets.', col: 'political activism' },
      { term: 'alienation', pos: 'n.', def: 'a feeling of isolation or estrangement from society', ex: 'Economic alienation among unemployed graduates fuels political polarisation.', col: 'social alienation' },
      { term: 'bureaucracy', pos: 'n.', def: 'a complex administrative system with many rules and officials', ex: 'Excessive bureaucracy delays asylum applications for years.', col: 'government bureaucracy' },
      { term: 'census', pos: 'n.', def: 'an official count of a population and its characteristics', ex: 'The census revealed a sharp increase in single-person households.', col: 'national census' },
      { term: 'diversity', pos: 'n.', def: 'the presence of many different social or cultural groups', ex: 'Workplace diversity policies must go beyond symbolic hiring targets.', col: 'cultural diversity' },
      { term: 'emancipation', pos: 'n.', def: 'the process of gaining freedom from legal or social restrictions', ex: 'Women\'s emancipation movements secured voting rights over several decades.', col: 'social emancipation' },
      { term: 'feminism', pos: 'n.', def: 'the advocacy of women\'s rights on grounds of equality', ex: 'Fourth-wave feminism uses social media to challenge everyday sexism.', col: 'feminist movement' },
      { term: 'homelessness', pos: 'n.', def: 'the condition of lacking stable, adequate housing', ex: 'Homelessness rose when short-term rentals displaced low-income tenants.', col: 'chronic homelessness' },
      { term: 'integration', pos: 'n.', def: 'the inclusion of groups into the broader social and economic life', ex: 'Refugee integration programmes combine language classes with job placement.', col: 'social integration' },
      { term: 'justice', pos: 'n.', def: 'fair treatment according to law and moral principles', ex: 'Restorative justice brings offenders and victims together to repair harm.', col: 'criminal justice' },
      { term: 'kinship', pos: 'n.', def: 'family relationships and the social bonds they create', ex: 'Kinship networks provide childcare where state services are weak.', col: 'kinship ties' },
      { term: 'legitimacy', pos: 'n.', def: 'general acceptance that authority is rightful and should be obeyed', ex: 'Corruption scandals eroded public legitimacy of electoral institutions.', col: 'political legitimacy' },
      { term: 'migration', pos: 'n.', def: 'movement of people from one place to another, often across borders', ex: 'Labour migration filled shortages in agriculture and elder care sectors.', col: 'international migration' },
      { term: 'norm', pos: 'n.', def: 'an expected standard of behaviour within a group', ex: 'Changing social norms reduced smoking in public spaces over thirty years.', col: 'social norm' },
      { term: 'patriarchy', pos: 'n.', def: 'a system where men hold primary power in institutions and families', ex: 'Scholars analyse how patriarchy shapes hiring and domestic labour division.', col: 'challenge patriarchy' },
      { term: 'quota', pos: 'n.', def: 'a fixed share or minimum number reserved for a group', ex: 'Parliamentary gender quotas increased female representation within two elections.', col: 'employment quota' },
      { term: 'refugee', pos: 'n.', def: 'a person forced to flee their country due to persecution or war', ex: 'Host nations debated how many refugee resettlement places to offer annually.', col: 'refugee camp' },
      { term: 'solidarity', pos: 'n.', def: 'unity and mutual support among people with shared interests', ex: 'Trade unions expressed solidarity with striking healthcare workers nationwide.', col: 'show solidarity' },
      { term: 'stereotype', pos: 'n.', def: 'an oversimplified and often unfair belief about a group', ex: 'Media stereotypes reinforce prejudice against minority youth.', col: 'gender stereotype' },
      { term: 'taboo', pos: 'n.', def: 'a subject considered unacceptable to discuss in a culture', ex: 'Breaking the taboo around mental illness encouraged more people to seek help.', col: 'cultural taboo' },
      { term: 'unemployment', pos: 'n.', def: 'the state of being without paid work despite seeking it', ex: 'Youth unemployment remained double the national average after the recession.', col: 'youth unemployment' },
      { term: 'volunteerism', pos: 'n.', def: 'the practice of offering unpaid help for community benefit', ex: 'Volunteerism surged during the pandemic when formal services were overwhelmed.', col: 'community volunteerism' },
      { term: 'xenophobia', pos: 'n.', def: 'dislike or prejudice against people from other countries', ex: 'Politicians condemned xenophobia following attacks on migrant shopkeepers.', col: 'rise in xenophobia' },
      { term: 'youth bulge', pos: 'n.', def: 'a large proportion of young people relative to other age groups', ex: 'A youth bulge can fuel innovation or instability depending on job creation.', col: 'demographic youth bulge' },
      { term: 'zeitgeist', pos: 'n.', def: 'the defining spirit or mood of a particular period', ex: 'The zeitgeist of the era favoured environmental accountability in business.', col: 'capture the zeitgeist' },
      { term: 'affordable housing', pos: 'n.', def: 'dwellings priced within reach of low- and middle-income households', ex: 'Cities lack affordable housing near employment centres and schools.', col: 'affordable housing crisis' },
      { term: 'civil disobedience', pos: 'n.', def: 'nonviolent refusal to obey laws regarded as unjust', ex: 'Civil disobedience during the march led to negotiated policy reforms.', col: 'acts of civil disobedience' },
      { term: 'disenfranchisement', pos: 'n.', def: 'deprivation of the right to vote or participate politically', ex: 'Felony disenfranchisement affects millions of citizens in several states.', col: 'voter disenfranchisement' },
      { term: 'egalitarian', pos: 'adj.', def: 'believing in or aiming for equal rights and opportunities', ex: 'Egalitarian societies invest heavily in public education and healthcare.', col: 'egalitarian principles' },
      { term: 'grassroots', pos: 'adj.', def: 'originating from ordinary people rather than elite leadership', ex: 'Grassroots campaigns mobilised neighbours to oppose the landfill expansion.', col: 'grassroots movement' },
      { term: 'hegemony', pos: 'n.', def: 'dominance of one group or state over others', ex: 'Cultural hegemony spreads through media exports and language education.', col: 'cultural hegemony' },
      { term: 'intersectionality', pos: 'n.', def: 'the overlap of social categories such as race, class, and gender', ex: 'Intersectionality explains why some women face compounded discrimination.', col: 'intersectional analysis' },
      { term: 'juvenile delinquency', pos: 'n.', def: 'illegal or antisocial behaviour by young people', ex: 'After-school programmes reduced juvenile delinquency in high-risk districts.', col: 'prevent juvenile delinquency' },
      { term: 'litigation', pos: 'n.', def: 'the process of taking legal action in court', ex: 'Civil litigation forced the company to compensate displaced residents.', col: 'civil litigation' },
      { term: 'multiculturalism', pos: 'n.', def: 'the coexistence and recognition of diverse cultural groups', ex: 'Canada\'s multiculturalism policy promotes inclusion without assimilation pressure.', col: 'state multiculturalism' },
      { term: 'neoliberal', pos: 'adj.', def: 'favouring free markets and reduced government intervention', ex: 'Neoliberal reforms privatised utilities but widened regional income gaps.', col: 'neoliberal agenda' },
      { term: 'philanthropy', pos: 'n.', def: 'donation of money or resources for public good', ex: 'Philanthropy funded scholarships but could not replace systemic school funding.', col: 'corporate philanthropy' },
      { term: 'social mobility', pos: 'n.', def: 'the ability to move between socioeconomic levels', ex: 'Weak social mobility suggests talent is wasted by unequal early education.', col: 'upward social mobility' }
    ]
  },
  {
    topic: 'Work',
    words: [
      { term: 'recruitment', pos: 'n.', def: 'the process of finding and hiring suitable employees', ex: 'Online recruitment platforms broadened the candidate pool for technical roles.', col: 'recruitment drive' },
      { term: 'remuneration', pos: 'n.', def: 'payment or compensation for work performed', ex: 'Executives defended remuneration packages amid layoffs in subsidiary firms.', col: 'fair remuneration' },
      { term: 'redundancy', pos: 'n.', def: 'dismissal because a job is no longer needed', ex: 'Factory redundancy left hundreds seeking retraining in green industries.', col: 'made redundant' },
      { term: 'productivity', pos: 'n.', def: 'the rate of output per unit of input in work', ex: 'Remote work policies affected productivity differently across departments.', col: 'labour productivity' },
      { term: 'probation', pos: 'n.', def: 'a trial period before permanent employment is confirmed', ex: 'She completed probation successfully and received a permanent contract.', col: 'on probation' },
      { term: 'pension', pos: 'n.', def: 'regular payments to a person after retirement from work', ex: 'Many workers fear their pension will not cover rising healthcare costs.', col: 'pension scheme' },
      { term: 'overtime', pos: 'n.', def: 'extra hours worked beyond the normal schedule', ex: 'Mandatory overtime in warehouses raised concerns about worker fatigue.', col: 'work overtime' },
      { term: 'freelance', pos: 'adj.', def: 'working independently for various clients rather than one employer', ex: 'Freelance designers enjoy flexibility but lack stable benefits.', col: 'freelance work' },
      { term: 'commute', pos: 'v.', def: 'to travel regularly between home and workplace', ex: 'Employees commute longer distances when affordable housing is scarce.', col: 'daily commute' },
      { term: 'delegation', pos: 'n.', def: 'assigning responsibility for tasks to subordinates', ex: 'Effective delegation frees managers to focus on strategic planning.', col: 'task delegation' },
      { term: 'downsizing', pos: 'n.', def: 'reducing the number of employees to cut costs', ex: 'Corporate downsizing prioritised short-term savings over institutional knowledge.', col: 'corporate downsizing' },
      { term: 'entrepreneur', pos: 'n.', def: 'a person who starts and runs a business, taking financial risk', ex: 'The entrepreneur secured venture capital after demonstrating market traction.', col: 'successful entrepreneur' },
      { term: 'gig economy', pos: 'n.', def: 'a labour market of short-term contracts and freelance work', ex: 'The gig economy offers flexibility but often excludes paid leave.', col: 'gig economy worker' },
      { term: 'harassment', pos: 'n.', def: 'unwelcome conduct that creates a hostile work environment', ex: 'The firm updated policies after several harassment complaints were upheld.', col: 'workplace harassment' },
      { term: 'incentive', pos: 'n.', def: 'something that motivates employees to improve performance', ex: 'Performance incentives aligned sales targets with quarterly revenue goals.', col: 'financial incentive' },
      { term: 'layoff', pos: 'n.', def: 'temporary or permanent dismissal of employees, often for economic reasons', ex: 'Mass layoffs followed the merger as duplicate roles were eliminated.', col: 'mass layoff' },
      { term: 'mentor', pos: 'n.', def: 'an experienced colleague who guides a less experienced worker', ex: 'A senior engineer agreed to mentor interns throughout the summer programme.', col: 'mentor programme' },
      { term: 'negotiation', pos: 'n.', def: 'discussion aimed at reaching agreement, especially on pay or terms', ex: 'Collective negotiation secured a modest wage increase for union members.', col: 'salary negotiation' },
      { term: 'onboarding', pos: 'n.', def: 'the process of integrating a new employee into an organisation', ex: 'Structured onboarding reduced early turnover among graduate hires.', col: 'employee onboarding' },
      { term: 'portfolio', pos: 'n.', def: 'a collection of work samples demonstrating skills and achievements', ex: 'Applicants submitted a digital portfolio showcasing design projects.', col: 'professional portfolio' },
      { term: 'qualification', pos: 'n.', def: 'a skill, certificate, or degree required for a job', ex: 'The role lists project-management qualification as highly desirable.', col: 'job qualification' },
      { term: 'resignation', pos: 'n.', def: 'the act of voluntarily leaving a job', ex: 'Her resignation followed disagreements over ethical sourcing policies.', col: 'submit one\'s resignation' },
      { term: 'retrenchment', pos: 'n.', def: 'dismissal of workers to reduce costs, especially in downturns', ex: 'Retrenchment in mining towns devastated local retail and services.', col: 'forced retrenchment' },
      { term: 'strike', pos: 'n.', def: 'a work stoppage by employees to press demands', ex: 'The strike halted production until management agreed to safer shifts.', col: 'go on strike' },
      { term: 'telecommuting', pos: 'n.', def: 'working from home using digital communication tools', ex: 'Telecommuting policies became permanent for staff in analytical roles.', col: 'telecommuting arrangement' },
      { term: 'underemployment', pos: 'n.', def: 'working in a job that does not fully use one\'s skills or hours', ex: 'Graduate underemployment suggests a mismatch between degrees and labour demand.', col: 'graduate underemployment' },
      { term: 'vacancy', pos: 'n.', def: 'an unfilled position available for employment', ex: 'The hospital advertised a vacancy for a bilingual nurse practitioner.', col: 'job vacancy' },
      { term: 'whistle-blower', pos: 'n.', def: 'a person who reports illegal or unethical activity in an organisation', ex: 'Laws protect the whistle-blower from retaliation after exposing fraud.', col: 'whistle-blower protection' },
      { term: 'workload', pos: 'n.', def: 'the amount of work assigned to a person or team', ex: 'Unrealistic workload contributed to burnout among emergency-room staff.', col: 'heavy workload' },
      { term: 'appraisal', pos: 'n.', def: 'a formal assessment of an employee\'s performance', ex: 'Annual appraisal feedback identified training needs for junior analysts.', col: 'performance appraisal' },
      { term: 'blue-collar', pos: 'adj.', def: 'relating to manual or industrial labour', ex: 'Blue-collar wages rose as skilled trades faced nationwide shortages.', col: 'blue-collar worker' },
      { term: 'white-collar', pos: 'adj.', def: 'relating to professional office-based work', ex: 'White-collar employees negotiated hybrid schedules after returning from lockdown.', col: 'white-collar job' },
      { term: 'colleague', pos: 'n.', def: 'a person with whom one works', ex: 'She collaborated with colleagues across three time zones on the merger.', col: 'trusted colleague' },
      { term: 'deadline', pos: 'n.', def: 'the latest time by which a task must be completed', ex: 'Missing the deadline cost the consultancy its largest government contract.', col: 'meet a deadline' },
      { term: 'empowerment', pos: 'n.', def: 'giving employees authority and confidence to make decisions', ex: 'Workplace empowerment increased innovation among frontline customer-service teams.', col: 'employee empowerment' },
      { term: 'flexitime', pos: 'n.', def: 'a system allowing employees to choose their working hours within limits', ex: 'Flexitime helped parents balance childcare with full-time careers.', col: 'flexitime arrangement' },
      { term: 'glass ceiling', pos: 'n.', def: 'an unacknowledged barrier preventing women from senior roles', ex: 'Despite equal hiring, a glass ceiling still limits promotion to executive boards.', col: 'break the glass ceiling' },
      { term: 'headhunt', pos: 'v.', def: 'to recruit a senior executive from another organisation', ex: 'The board decided to headhunt a CEO with turnaround experience.', col: 'headhunt talent' },
      { term: 'industrial action', pos: 'n.', def: 'protest by workers such as strikes or slowdowns', ex: 'Industrial action ended when employers improved pension contributions.', col: 'take industrial action' },
      { term: 'job satisfaction', pos: 'n.', def: 'the contentment a person feels about their work', ex: 'Autonomy and purpose predict job satisfaction more than salary alone.', col: 'high job satisfaction' },
      { term: 'knowledge worker', pos: 'n.', def: 'an employee whose main capital is expertise and information', ex: 'Knowledge workers demand continuous learning budgets from employers.', col: 'knowledge worker productivity' },
      { term: 'labour union', pos: 'n.', def: 'an organisation that represents workers in negotiations with employers', ex: 'The labour union bargained for safer conditions in garment factories.', col: 'join a labour union' },
      { term: 'moonlighting', pos: 'n.', def: 'holding a second job, often secretly, in addition to one\'s main job', ex: 'Moonlighting rose among teachers supplementing inadequate public salaries.', col: 'moonlighting job' },
      { term: 'offshoring', pos: 'n.', def: 'relocating business processes to another country to reduce costs', ex: 'Offshoring customer support reduced expenses but angered domestic workers.', col: 'offshoring operations' },
      { term: 'presenteeism', pos: 'n.', def: 'working while ill or beyond required hours, reducing effectiveness', ex: 'Presenteeism spreads illness and lowers overall organisational output.', col: 'culture of presenteeism' },
      { term: 'quota', pos: 'n.', def: 'a fixed amount of work or sales a person must achieve', ex: 'Aggressive sales quotas encouraged unethical practices among regional managers.', col: 'sales quota' },
      { term: 'restructuring', pos: 'n.', def: 'organisational change to improve efficiency, often involving job cuts', ex: 'Corporate restructuring merged divisions and eliminated duplicate management layers.', col: 'company restructuring' },
      { term: 'severance', pos: 'n.', def: 'pay and benefits given to an employee upon termination', ex: 'Negotiated severance packages eased transitions for displaced manufacturing staff.', col: 'severance pay' },
      { term: 'turnover', pos: 'n.', def: 'the rate at which employees leave and are replaced', ex: 'High turnover in call centres reflected stressful targets and low pay.', col: 'staff turnover' },
      { term: 'vocational training', pos: 'n.', def: 'instruction that prepares people for specific trades or careers', ex: 'Partnerships with firms ensured vocational training matched industry skill needs.', col: 'vocational training programme' }
    ]
  }
];

module.exports = { VOCAB_TOPICS };
