/**
 * CSS/PMS English Essay Guide — model essays 6–10 (part 2 of 2).
 * Each essay targets 800–900 words (~850).
 */

const ESSAYS_PART2 = [
  {
    title: 'Essay 6: Technology Impact on Society',
    text:
      'When the Pakistan Telecommunication Authority reported internet penetration crossing roughly 45 percent of the population in the early 2020s, the figure sounded like progress. Yet penetration is not inclusion. Millions remain offline while urban centres absorb fibre, 4G towers, and cheap smartphones at speed. Technology is reshaping Pakistani society faster than law, schools, and labour markets can adapt — creating opportunity, anxiety, and a widening digital divide in the same decade.\n\n' +
      'Connectivity has altered how citizens learn, trade, and protest. Social media platforms host tens of millions of Pakistani accounts; PTA estimates placed active social media users above 70 million by 2023, with Facebook, YouTube, and TikTok among the most-used applications. Mobile broadband subscriptions exceeded 130 million by 2024, yet many SIMs sit in multi-SIM handsets while household sharing masks uneven access. WhatsApp groups coordinate relief after floods; YouTube tutors replace absent teachers in remote districts; TikTok launches careers and controversies overnight. The upside is real: diaspora remittances move through mobile wallets; women in purdah-restricted areas access health information; small vendors sell on Facebook without shop rent. JazzCash and Easypaisa brought millions into basic financial inclusion. Telemedicine pilots in KP and Punjab proved lifesaving during COVID-19 lockdowns. The downside is equally visible. Disinformation spreads during elections; honour-related violence has been linked to leaked videos; adolescents encounter radical content with minimal gatekeeping. Society has gained a public square without agreeing on its rules.\n\n' +
      'Federal initiatives such as the Digital Pakistan vision (2018 onward) promised e-governance, startup funding, and IT park expansion. Progress is uneven: some ministries digitised payments, but land records and police FIRs still trap citizens in paper queues. Startups raised venture capital in fintech and logistics, yet exits remain rare. The State Bank\'s regulatory sandbox allowed digital banks; still, cash dominates bazaars. Technology policy must connect ambition to provincial execution — fibre to the village, not only incubators in Islamabad.\n\n' +
      'Artificial intelligence intensifies the labour question. Globally, AI threatens routine white-collar tasks — data entry, basic coding, customer support — even as Pakistan still struggles to formalise its existing workforce. The IT export sector earned record remittances in recent years, yet that success employs a narrow graduate layer in Karachi, Lahore, and Islamabad. For the majority, technology means platform gig work: ride-hailing, food delivery, freelance graphics on insecure contracts without pensions. Government skills programmes and boot camps help, but they cannot absorb the youth entering the market each year. The risk is a two-tier economy: AI-augmented professionals linked to global clients, and everyone else competing for diminishing routine jobs.\n\n' +
      'The urban–rural digital divide remains Pakistan\'s sharpest inequality after land and water. Urban internet penetration in major cities approaches two-thirds of residents; many rural tehsils remain below 20 percent, with unreliable electricity undermining even basic charging. Girls drop out when families fear online moral hazard; teachers lack training to blend classrooms with tablets distributed under provincial schemes. Agriculture — still employing roughly 38 percent of workers — receives too little precision-tech extension: weather apps exist, but credit, cold storage, and market access do not follow the fibre line. Without last-mile infrastructure and digital literacy in Sindhi, Pashto, Balochi, and Punjabi, technology replicates centre–periphery dominance in a new medium.\n\n' +
      'Governance and ethics lag behind adoption. The Personal Data Protection Bill moved through parliament in fits and starts; cybercrime units under the FIA remain understaffed relative to complaint volume. Tax authorities chase e-commerce revenue while traders demand clarity on withholding on platforms. Courts face novel cases: deepfakes, crypto fraud, online harassment of journalists. The Prevention of Electronic Crimes Act 2016 criminalised online speech broadly; activists argue it silences dissent more than it protects women from harassment. Meanwhile, state agencies themselves use surveillance and firewall tools during security operations, raising legitimate needs but also chilling political speech. A coherent national digital policy must balance innovation with rights — transparent content regulation, judicial oversight of takedowns, and competition law that prevents platform monopolies from capturing Pakistani advertising spend now exceeding tens of billions of rupees annually.\n\n' +
      'Health and education illustrate dual impact. During COVID-19, Radio Pakistan and SMS alerts reached areas without broadband; simultaneously, students in Balochistan missed exams for months without devices. Ed-tech firms sell tablets, but pedagogy remains rote. Hospitals in Lahore use electronic records while rural BHUs lack stable oxygen, let alone Wi-Fi. Technology should not become an excuse to shrink public service budgets.\n\n' +
      'Education is the decisive lever. Curriculum reform should treat digital citizenship as core, not extracurricular: source verification, privacy hygiene, and ethical AI use. Public–private partnerships can extend community Wi-Fi to union council offices and women\'s vocational centres. Industry must align apprenticeships with cloud, cybersecurity, and green-tech maintenance — trades that survive automation. None of this requires rejecting tradition; it requires equipping citizens to negotiate modernity on their terms.\n\n' +
      'Technology does not determine society\'s fate; institutions and choices do. Pakistan can harness connectivity to reduce isolation, diversify exports, and hold power accountable — or allow the digital divide to harden into a caste line between plugged-in metros and disconnected hinterlands. The evidence from the last decade is mixed. The task of the next is to make access universal, skills relevant, and regulation democratic — so that the screen reflects the republic, not only its elites.',
    comment:
      'Band A: opens with PTA-scale data, balances opportunities and harms, and treats AI as a labour-governance issue rather than hype. Strong Pakistan specificity (language divide, gig economy, provincial tablet schemes). Could add one named policy (e.g. Digital Pakistan initiative) for even sharper anchoring.',
  },
  {
    title: 'Essay 7: Water Crisis in Pakistan',
    text:
      'Pakistan was once water-abundant by global standards. At independence, per capita renewable freshwater availability stood near 5,000 cubic metres annually — well above the water-stress threshold of 1,700 cubic metres. By 2020, estimates from the Pakistan Council of Research in Water Resources and international agencies placed availability closer to 1,000 cubic metres, plunging the country into the "scarcity" band. Population growth, inefficient agriculture, climate variability, and upstream politics converged. Water is no longer a background resource; it is the defining constraint on food security, energy, and inter-provincial harmony.\n\n' +
      'Population crossed 240 million in 2024, compressing per capita shares even if absolute river flows held steady — they have not. The World Resources Institute ranked Pakistan among the most water-stressed countries globally. Competition between provinces is litigated in the Council of Common Interests and on streets: Punjab\'s upstream withdrawals meet Sindh\'s downstream salinity complaints each dry season. Climate models project erratic monsoons — intense bursts like 2022, punctuated by drought years that punish rain-fed lands in Thar and Kohistan.\n\n' +
      'Agriculture consumes roughly 90 percent of diverted freshwater, mostly through flood irrigation on wheat, rice, and sugarcane. Canal losses to seepage and evaporation remain enormous; sugarcane and rice in semi-arid zones embody ecological mismatch sustained by political patronage. Groundwater extraction in Punjab and Sindh has lowered water tables alarmingly; saline intrusion threatens coastal aquifers. The 2022 floods ironically dramatised surplus and shortage together: millions drowned in monsoon excess while storage reservoirs and soil moisture management remained inadequate for dry years. Pakistan contributes less than one percent to global greenhouse gases yet ranks among the most climate-vulnerable states — glacial melt in the Hindu Kush–Karakoram–Himalaya arc feeds the Indus system that 240 million people depend on, even as retreating glaciers initially swell flows before long-term decline.\n\n' +
      'International law frames the crisis through the Indus Waters Treaty of 1960 between Pakistan and India, brokered by the World Bank. The treaty allocated the three western rivers (Indus, Jhelum, Chenab) to Pakistan and the three eastern rivers to India, with dispute mechanisms on storage and run-of-river projects. It has survived wars and standoffs — a diplomatic achievement — yet it strains under new realities: Indian hydro projects on western tributaries, Pakistani concerns about timing and sediment, and climate-driven flow uncertainty not imagined in 1960. Kishanganga and Ratle disputes reached arbitration and negotiation repeatedly. Pakistan cannot discuss internal dams without referencing external flows; every provincial storage plan is read through the lens of drops denied or delayed upstream.\n\n' +
      'Domestic politics centres on dams and distribution. Kalabagh Dam on the Indus in Khyber Pakhtunkhwa became a symbol of Punjab-centred federal distrust: Sindh fears reduced downstream flows; KP communities resist submergence and seismic risk; political parties weaponise the project in elections while storage capacity stays stagnant. Meanwhile, Mangla and Tarbela age; sediment reduces live storage; Bhasha Dam construction progresses slowly under fiscal and security pressures. Sindh\'s grievances over Taunsa–Panjnad and Kotri barrage shortages fuel separatist rhetoric; Balochistan\'s chronically underfunded irrigation schemes highlight provincial inequality. Water policy is federalism in liquid form.\n\n' +
      'Neighbouring comparisons sharpen urgency. India and Bangladesh invest in barrages and delta management; Afghanistan\'s irrigation rehabilitation affects Kabul River tributaries. Within Pakistan, the Diamer-Bhasha and Mohmand dams symbolise delayed consensus. Desalination for Karachi remains expensive and energy-hungry — a coastal city of 20 million cannot rely on the sea alone. Rainwater harvesting in Islamabad housing societies shows local initiative; national scale requires building codes enforced by municipalities starved of funds.\n\n' +
      'Demand management lags behind supply engineering. Drip irrigation, laser levelling, and crop substitution toward oilseeds and pulses receive pilot funding but not scale. Urban utilities lose half of treated water to leaks and theft; industrial effluent poisons the Ravi and Kabul tributaries. Pricing remains politically toxic: flat-rate canal water subsidises large landowners. The National Water Policy 2018 articulated integrated management, but implementation fragments across provinces with weak monitoring. Courts have intervened — notably on Karachi\'s water theft and river pollution — yet judicial orders cannot replace metering and maintenance.\n\n' +
      'A credible response combines storage, efficiency, and diplomacy. Build consensus storage where geology and equity align, prioritising Bhasha and smaller run-of-river schemes with transparent provincial benefit-sharing. Modernise irrigation through farmer cooperatives and credit for micro-irrigation. Treat wastewater in cities and enforce industrial standards. Renegotiate treaty technical schedules for climate appendices without reopening partition-era zero-sum politics. Invest in glacial monitoring and early flood warning — lessons from 2022 must become infrastructure, not memories.\n\n' +
      'Pakistan\'s water crisis is not a future headline; it is present in stunted children from diarrhoea, in cotton fields salted by overpumping, in riots at barrage headworks. Women and girls walk miles for drinking water in Tharparkar while lawns are watered in gated communities — inequality measured in litres. Per capita availability will not return to 1950 levels; the goal is equitable survival at 1,000 cubic metres through science, law, and political courage. Without that, development plans remain ink on dry paper.',
    comment:
      'Band A: integrates historical per capita decline, treaty context, and Kalabagh federal politics into one argument. Strong use of percentages and institutions (PCRWR, World Bank). Examiner-ready structure: hydrology, agriculture, treaty, dams, solutions. A single recent court case name would add polish.',
  },
  {
    title: 'Essay 8: Unemployment Solutions in Pakistan',
    text:
      'Pakistan\'s demographic dividend is often praised and rarely employed. Roughly 64 percent of the population is under thirty; the median age hovers near 22. More than two million young people enter the labour force annually while net job creation often falls short. The Pakistan Bureau of Statistics Labour Force Survey reported overall unemployment near 6–7 percent in recent rounds, but youth rates and female unemployment tell a harsher story — educated urban youth face double-digit joblessness in surveys by the Pakistan Institute of Development Economics. Underemployment — part-time, seasonal, or below qualification — affects far larger numbers than headline rates admit. Graduates queue for government clerical posts while factories report skill mismatches. The paradox is not a shortage of people but a shortage of productive, fairly paid jobs — and a policy discourse that confuses announcements with outcomes.\n\n' +
      'The graduate unemployment trap reflects education–market misalignment. Universities expanded enrolment — often exceeding four percent of GDP in household spending even when public investment lagged — without linking departments to industry pipelines. Arts and social science graduates flood a market hungry for technicians, nurses, and digital marketers. Public-sector hiring freezes and court-blocked recruitment drives intensify obsession with "government job" security. Private firms prefer experienced hires; internships are unpaid or nepotistic. The result: educated unemployment that fuels cynicism and brain drain. Reform must tighten quality assurance, fund polytechnics and apprenticeships, and reward universities for graduate placement, not enrolment alone.\n\n' +
      'The National Employment Policy and provincial youth internship schemes exist on paper; delivery is patchy. Sindh and Punjab launched skill development authorities, but placement tracking is weak. CSS aspirants and MPhil holders compete for peon posts — a signal that credential inflation outran job quality. Vocational stigma persists: parents prefer degrees without employability. Changing culture requires celebrating technicians who maintain CPEC power plants and export-oriented stitching units alike.\n\n' +
      'CPEC symbolised employment hope after 2015: energy projects, Gwadar port, road corridors. Thousands worked in construction; power plants eased load-shedding. Yet CPEC-linked direct jobs peaked in the build phase; operations employ fewer, often specialised, workers. Special Economic Zones progressed unevenly; Chinese firms sometimes import skilled labour while local subcontractors handle low-margin tasks. The lesson is not to reject CPEC but to domesticate value chains — component manufacturing, maintenance, logistics — through joint ventures and mandatory training quotas. Infrastructure without industrial policy repeats the motorway mistake: faster travel, unchanged factory share of GDP near 13 percent.\n\n' +
      'The informal sector absorbs most Pakistanis — street vendors, domestic workers, farmhands, home-based stitchers — without contracts, social insurance, or productivity tools. Ehsaas and BISP provide cash relief; they do not transform informal survival into SME growth. Registration drives, access to microfinance at single-digit spreads, and simplified tax for firms below turnover thresholds could formalise millions gradually. Cooperatives in dairy, horticulture, and garments pool risk for small producers. Here unemployment solutions overlap with credit and energy policy: a tailor with twelve hours of load-shedding cannot scale.\n\n' +
      'Agriculture and services remain job engines if modernised. Agro-processing near farms cuts post-harvest loss; cold chains for potatoes and mangoes employ cold-storage technicians. Tourism along heritage corridors in Punjab and KP needs trained guides and hospitality standards. Remote work export policies can spread IT earnings beyond three cities if broadband and co-working hubs reach second-tier towns. Women\'s labour force participation near 22 percent represents untapped capacity: childcare support, safe transport, and anti-harassment enforcement are employment policies disguised as social issues.\n\n' +
      'Entrepreneurship policy must move beyond loan schemes. The Kamyab Jawan Programme and SME credit lines helped some borrowers, but collateral requirements exclude first-generation founders. Venture investment in logistics and agri-tech could absorb engineers if intellectual property enforcement improved. National Vocational and Technical Training Commission centres should partner with exporters for certified welding, garment CAD, and solar installation — trades with regional demand.\n\n' +
      'Population policy intersects employment. Family planning uptake remains low in high-fertility districts; health workers connect contraception to maternal health, not to labour markets. Delaying the demographic peak by even five years would ease pressure on schools and jobs. Meanwhile, overseas employment — roughly 800,000 workers proceeded abroad annually pre-pandemic — relieves domestic pressure but drains skilled youth; remittances help balances, not industrial upgrading at home.\n\n' +
      'Macro stability underpins micro hiring. Inflation above 20 percent in 2022–23 eroded real wages; firms froze headcount. Repeated IMF programmes since 1988 imposed fiscal tightening that slowed public investment — yet without tax reform, the state cannot fund skills or infrastructure. A sustainable path raises documented taxpayers, cuts power tariffs for exporters, and targets textile productivity rather than quota chasing alone. Export stagnation in garments reflects outdated machinery and buyer concentration in a few markets; diversification into engineering goods, pharmaceuticals, and IT services spreads risk and jobs.\n\n' +
      'Unemployment in Pakistan is solvable only as a system problem: align education with trades and technology; capture CPEC downstream value; formalise the informal majority; and stabilise prices so firms invest. Youth are not a burden; they are inventory waiting for a supply chain. Treat them as consumers of hope alone, and elections will hear their frustration long after the last ribbon-cutting on an empty industrial estate.',
    comment:
      'Band A: links youth bulge, graduate mismatch, CPEC reality check, and informal sector — exactly the multidimensional answer CSS expects. Good statistics with cautious wording ("roughly", "many years"). Adding one Labour Force Survey year would strengthen evidence line further.',
  },
  {
    title: 'Essay 9: Media and Democracy in Pakistan',
    text:
      'Democracy requires more than ballots; it requires witnesses. A free press checks corruption, explains policy, and amplifies voices excluded from parliament. In Pakistan, media expanded explosively — private satellite channels after 2002, digital newsrooms, YouTube journalists — even as Reporters Without Borders ranked the country near 150 out of 180 countries on its World Press Freedom Index in recent editions (approximately 152 in 2023, slipping from the 140s a decade earlier). That gap between vibrant noise and structural freedom defines media\'s troubled relationship with democracy.\n\n' +
      'Historical memory matters. Under Zia-ul-Haq, press ordinances criminalised dissent; journalists were flogged. The 1990s saw alternating governments tolerate partisan newspapers while punishing opponents. Pervez Musharraf\'s era combined liberalisation of TV licences with emergency curbs in 2007. Civilian governments since 2008 promised media freedom in charters yet relied on advertising cuts and regulatory pressure when coverage hurt. Each cycle taught the same lesson: institutions matter more than personalities. Without legal protection, the next crisis will silence the next channel.\n\n' +
      'Ownership concentration undermines pluralism. A handful of conglomerates and family groups — including major groups headquartered in Karachi and Lahore — dominate ratings and advertising revenue; cross-ownership links television, print, and telecom interests. Government advertising, worth billions of rupees annually, becomes a soft subsidy and a soft leash: channels competing for ministry ads self-limit investigations. Editors know that critical coverage of proprietors\' other businesses — real estate, banking, government contracts — carries career cost. Prime-time talk shows polarise politics into theatrical duels, often favouring the party currently aligned with establishment preferences. Investigative units survive on donor-funded digital startups or exile-based platforms, while mainstream bulletins recycle official statements. The Pakistan Federal Union of Journalists issues statements; unity fractures under economic pressure. Democracy needs diversity of owners, not only diversity of shouting.\n\n' +
      'PEMRA, the electronic media regulator, embodies the tension between standards and control. Created in 2002 to licence channels and enforce decency codes, it became an instrument of suspension during crises — Geo TV faced closure orders in 2007 and again in 2018; other networks received show-cause notices after interviews with opposition leaders. Licences carry moralised content rules on dress and language; delays in renewal chill editorial planning. Cable operators selectively drop channels during tense periods. Journalists face defamation suits, anti-terror charges for reporting militancy, and assault with impunity in provincial interiors — Daniel Pearl\'s murder (2002) remains a symbol of global risk; local reporters in Balochistan and KPK face daily threats. RSF documented killings and abductions over decades; impunity index remains dismal. Self-censorship spreads faster than written bans: reporters omit lines, anchors soften questions, social media managers delete tweets preemptively.\n\n' +
      'Print media, though declining in circulation, sets morning agendas for TV. English dailies reach elites; Urdu press reaches masses. Both feel economic squeeze as advertising shifts to Meta and Google, starving investigative desks. Yet it was newspapers that broke stories on Panama Papers links (2016) and governance scandals, proving that ownership limits need not eliminate all courage — only that courage becomes exceptional rather than routine.\n\n' +
      'Digital media outpaced law. Citizens film police encounters; clerics mobilise on WhatsApp; parties run troll farms. The state responded with social media rules requiring removal within hours and data localisation debates. Without independent oversight, such powers risk silencing dissent more than hate speech. Meanwhile, disinformation undermines electoral democracy — fake quotes, doctored videos, and foreign-influence anxieties appeared in 2018 and 2024 cycles. Media literacy is defensive infrastructure; regulators should target coordinated inauthentic behaviour, not every critic of policy.\n\n' +
      'Positive forces persist. Court interventions occasionally protected press freedom; some channels aired missing-persons stories despite pressure. Women anchors and regional language outlets expanded representation. Exile journalism keeps stories alive abroad. Public interest litigation forced transparency on privatisation and environment. For every silenced columnist, a blogger documents flood relief corruption in Sindh. Democracy\'s immune system is weak but not absent.\n\n' +
      'Reform should follow democratic principles, not security reflex alone. PEMRA must be statutorily independent, with bipartisan appointments and published suspension reasons subject to judicial review. Ownership caps and disclosure rules would reduce hidden influence. Decriminalise defamation for public-interest reporting; investigate attacks on journalists through dedicated federal units. Allocate spectrum and advertising fairly between state and private broadcasters. Support public service broadcasting that educates, not only propagandises. Digital rules need sunset clauses and appeal courts.\n\n' +
      'International benchmarks keep pressure visible. RSF, Committee to Protect Journalists, and UNESCO reports remind parliament that rankings affect investment confidence. Pakistan compares poorly with India and Bangladesh on press freedom scores, though all South Asian states face violence against reporters. Diplomatic missions occasionally advocate for journalist safety; consistency requires domestic legal reform, not episodic concern.\n\n' +
      'Media and democracy rise or fall together. When citizens cannot trust what they see, they trust conspiracy instead of constitution. Pakistan\'s ranking near the bottom of press freedom indices is not destiny — it is a policy choice repeated daily. A republic serious about democratic consolidation will protect witnesses before warriors, and facts before favourites.',
    comment:
      'Band A: connects RSF ranking, ownership economics, and PEMRA with democratic theory — not a rant. Balanced "positive forces" paragraph shows nuance examiners reward. Could cite a specific PEMRA suspension year for extra marks.',
  },
  {
    title: 'Essay 10: Economic Challenges in Pakistan',
    text:
      'Pakistan\'s economy in the mid-2020s feels familiar: another IMF programme, another rupee slide, another finance minister promising consolidation. Public debt approached 70 percent of GDP by fiscal 2023–24, with total debt and liabilities exceeding 75 percent when guarantees to state-owned enterprises are included. External debt servicing consumed a large share of federal revenue, crowding out development. The current account deficit exceeded $17 billion in fiscal 2021–22 before narrowing under import bans and remittance inflows; the rupee fell from roughly 180 to 300 per dollar between 2022 and 2024, importing inflation. These are not abstract ratios; they translate into school fees paid in devalued rupees, factories idled for lack of dollars, and youth who measure progress in remittance receipts from Gulf relatives rather than local wages.\n\n' +
      'Fiscal weakness is structural. Tax-to-GDP ratios linger near 9–10 percent — among the lowest in emerging Asia — while exemptions for real estate, agriculture, and retail persist. Circular debt in power and gas exceeds trillions of rupees, bleeding budgets and discouraging investment. Loss-making SOEs — PIA, steel mills, distribution companies — absorb guarantees. Defence and debt servicing crowd out development spending; education and health remain under 3 percent of GDP combined. Without documented broadening of the tax base, every IMF target becomes a slash to growth-linked spending, feeding political resistance and programme interruption.\n\n' +
      'The current account tells a story of import dependence. Oil, LNG, edible oil, and machinery dominate the import bill; textiles still provide roughly 60 percent of goods export earnings — a dangerous concentration. When global cotton prices spike or buyers shift to Bangladesh and Vietnam, Pakistan\'s margin vanishes. Remittances above $30 billion annually are a lifeline, stabilising the rupee more reliably than exports. Yet remittance-led stability masks productivity stagnation: firms lack scale, technology upgrades, and trade facilitation at ports where clearance delays erode competitiveness.\n\n' +
      'IMF programmes recur like seasons — from structural adjustment in the late 1980s to the 2013 Extended Fund Facility, the 2019 programme interrupted by COVID, and the 2023 Stand-By Arrangement nearing $3 billion. Conditionality targets fiscal deficits, energy tariff rationalisation, and market-determined exchange rates. Governments sign in crisis, loosen in recovery, and return at the next shock. The Fund is not villain but mirror: Pakistan requests balance-of-payments support because savings and investment rates are too low to fund development alone. The political failure is incomplete reform between crises — privatisation stalled, power theft endemic, and elite capture of subsidised credit.\n\n' +
      'Textile export stagnation illustrates micro–macro links. Pakistan exported roughly $15–16 billion in textiles annually in recent years — still the largest export category, yet growth plateaued while Bangladesh gained EU market share. Garments face quality audits, green compliance, and fast-fashion speed abroad; local units run on obsolete looms and informal labour. Gas and electricity tariffs priced in dollars after devaluation squeeze mills in Faisalabad and Karachi. Cotton crop failures and flooding raised input costs. Trade agreements with China (FTA), Malaysia, and others remain underutilised because firms lack diversification capacity and rules-of-origin knowledge. Solutions include technology upgradation funds, skill centres for cutting and compliance, and moving up the value chain to branded apparel and technical textiles. Parallel tracks — IT services crossing $2 billion exports, food processing, surgical goods in Sialkot — prove diversification possible when clusters receive reliable energy and customs facilitation at Karachi Port and Port Qasim.\n\n' +
      'The State Bank raised policy rates sharply to tame inflation, crushing demand. Fiscal deficits near 7–8 percent of GDP before consolidation deals left little room for public investment in transmission lines or export estates. Privatisation of DISCOs and PIA stalled in parliament and courts. Elite agricultural income remains undertaxed while salaried classes bear withholding burdens — a political economy that IMF letters mention but governments hesitate to confront.\n\n' +
      'Inflation and interest rates crushed 2022–23: policy rates above 20 percent slowed construction and car loans; food inflation hurt wage earners. Climate shocks — floods, heat — raised import bills for food and recovery materials. Geopolitical rents from Afghanistan transit or Middle East alliances offer tactical relief, not industrial strategy. Long-term growth near 2–3 percent cannot absorb two million new workers yearly; unemployment and informality fester.\n\n' +
      'A sustainable economic agenda is known if politically difficult: document the economy through GST and property valuation; restructure SOEs with transparent timelines; invest in export zones with reliable utilities; protect the poor through targeted cash transfers, not blanket subsidies; and complete IMF benchmarks while legislating reforms parliament cannot reverse each election. Debt-to-GDP must fall through growth and revenue, not default alone. Pakistan\'s challenge is not ignorance of remedies but the coalition required to implement them against vested comfort.\n\n' +
      'Regional integration offers options if pursued strategically. SAARC trade underperformed for decades; bilateral routes with Afghanistan and Central Asia reopened after 2021 but remain volatile. RCEP-style participation is distant; near-term gains lie in fixing customs, reducing smuggling at borders, and certifying halal food exports for Gulf markets already linked by remittance flows.\n\n' +
      'Economic sovereignty in the twenty-first century is earned through productivity, not slogans. Until exports diversify and taxes widen, the republic will cycle between Fund missions and fragile calm — democratic in form, precarious in household finance.',
    comment:
      'Band A: integrates debt, tax, current account, IMF chronology, and textile concentration with household-level impact. Strong macro–micro linkage. For top marks, add one fiscal year figure for remittances or exact debt-to-GDP from Economic Survey.',
  },
];

module.exports = { ESSAYS_PART2 };
